name: NewSky
main: org.me.newsky.NewSky
version: '${project.version}'
api-version: 1.20
authors: [ TonyPak ]
commands:
  island:
    description: Island command
    usage: /<command>
    permission: gitsync.gitsync
permissions:
  island.island:
    description: Allows the user to use the /island command
    default: op