name: NewSky
main: org.me.newsky.NewSky
version: '${project.version}'
api-version: 1.20
authors: [ kit8379 ]
depend:
  - 'SlimeWorldManager'
softdepend:
  - 'Vault'
  - 'PlaceholderAPI'
libraries:
  - 'com.mysql:mysql-connector-j:${mysql.version}'
  - 'com.zaxxer:HikariCP:${hikari.version}'
  - 'redis.clients:jedis:${jedis.version}'
commands:
  island:
    description: Island command
    usage: /<command>
    permission: island.player
    aliases: [ is ]
  islandadmin:
    description: Island admin command
    usage: /<command>
    permission: island.admin
    aliases: [ isadmin ]
permissions:
  island.player:
    description: Allows the user to use the /island command
    default: true
  island.admin:
    description: Allows the user to use the /islandadmin command
    default: op
