name: NewSky
main: org.me.newsky.NewSky
version: '${project.version}'
api-version: 1.20
authors: [ TonyPak ]
depend:
  - VoidGen
  - Multiverse-Core
libraries:
  - 'redis.clients:jedis:${jedis_version}'
  - 'com.mysql:mysql-connector-java:${mysql_driver_version}'
  - 'com.zaxxer:HikariCP:${hikari_version}'
commands:
  island:
    description: Island command
    usage: /<command>
    permission: island.command
    aliases: [is]
  islandadmin:
    description: Island admin command
    usage: /<command>
    permission: island.admin
    aliases: [isadmin]
permissions:
  island.command:
    description: Allows the user to use the /island command
    default: true
  island.admin:
    description: Allows the user to use the /islandadmin command
    default: op